[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "delay brisk law urban slide exhibit wrestle agent timber tail yard nut lecture luxury fence marine proud shiver club praise symptom aerobic lunch void "
